//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Shippo.Models.Requests
{
    using Newtonsoft.Json.Linq;
    using Newtonsoft.Json;
    using Shippo.Models.Components;
    using Shippo.Utils;
    using System.Collections.Generic;
    using System.Numerics;
    using System.Reflection;
    using System;
    

    public class CreateTransactionRequestBodyType
    {
        private CreateTransactionRequestBodyType(string value) { Value = value; }

        public string Value { get; private set; }
        public static CreateTransactionRequestBodyType TransactionCreateRequest { get { return new CreateTransactionRequestBodyType("TransactionCreateRequest"); } }
        
        public static CreateTransactionRequestBodyType InstantTransactionCreateRequest { get { return new CreateTransactionRequestBodyType("InstantTransactionCreateRequest"); } }
        
        public static CreateTransactionRequestBodyType Null { get { return new CreateTransactionRequestBodyType("null"); } }

        public override string ToString() { return Value; }
        public static implicit operator String(CreateTransactionRequestBodyType v) { return v.Value; }
        public static CreateTransactionRequestBodyType FromString(string v) {
            switch(v) {
                case "TransactionCreateRequest": return TransactionCreateRequest;
                case "InstantTransactionCreateRequest": return InstantTransactionCreateRequest;
                case "null": return Null;
                default: throw new ArgumentException("Invalid value for CreateTransactionRequestBodyType");
            }
        }
        public override bool Equals(object? obj)
        {
            if (obj == null || GetType() != obj.GetType())
            {
                return false;
            }
            return Value.Equals(((CreateTransactionRequestBodyType)obj).Value);
        }

        public override int GetHashCode()
        {
            return Value.GetHashCode();
        }
    }


    /// <summary>
    /// Examples.
    /// </summary>
    [JsonConverter(typeof(CreateTransactionRequestBody.CreateTransactionRequestBodyConverter))]
    public class CreateTransactionRequestBody {
        public CreateTransactionRequestBody(CreateTransactionRequestBodyType type) {
            Type = type;
        }

        [SpeakeasyMetadata("form:explode=true")]
        public TransactionCreateRequest? TransactionCreateRequest { get; set; }

        [SpeakeasyMetadata("form:explode=true")]
        public InstantTransactionCreateRequest? InstantTransactionCreateRequest { get; set; }

        public CreateTransactionRequestBodyType Type { get; set; }


        public static CreateTransactionRequestBody CreateTransactionCreateRequest(TransactionCreateRequest transactionCreateRequest) {
            CreateTransactionRequestBodyType typ = CreateTransactionRequestBodyType.TransactionCreateRequest;

            CreateTransactionRequestBody res = new CreateTransactionRequestBody(typ);
            res.TransactionCreateRequest = transactionCreateRequest;
            return res;
        }

        public static CreateTransactionRequestBody CreateInstantTransactionCreateRequest(InstantTransactionCreateRequest instantTransactionCreateRequest) {
            CreateTransactionRequestBodyType typ = CreateTransactionRequestBodyType.InstantTransactionCreateRequest;

            CreateTransactionRequestBody res = new CreateTransactionRequestBody(typ);
            res.InstantTransactionCreateRequest = instantTransactionCreateRequest;
            return res;
        }

        public static CreateTransactionRequestBody CreateNull() {
            CreateTransactionRequestBodyType typ = CreateTransactionRequestBodyType.Null;
            return new CreateTransactionRequestBody(typ);
        }

        public class CreateTransactionRequestBodyConverter : JsonConverter
        {

            public override bool CanConvert(System.Type objectType) => objectType == typeof(CreateTransactionRequestBody);

            public override bool CanRead => true;

            public override object? ReadJson(JsonReader reader, System.Type objectType, object? existingValue, JsonSerializer serializer)
            {
                var json = JRaw.Create(reader).ToString();
                if (json == "null")
                {
                    return null;
                }

                var fallbackCandidates = new List<(System.Type, object, string)>();

                try
                {
                    return new CreateTransactionRequestBody(CreateTransactionRequestBodyType.TransactionCreateRequest)
                    {
                        TransactionCreateRequest = ResponseBodyDeserializer.DeserializeUndiscriminatedUnionMember<TransactionCreateRequest>(json)
                    };
                }
                catch (ResponseBodyDeserializer.MissingMemberException)
                {
                    fallbackCandidates.Add((typeof(TransactionCreateRequest), new CreateTransactionRequestBody(CreateTransactionRequestBodyType.TransactionCreateRequest), "TransactionCreateRequest"));
                }
                catch (ResponseBodyDeserializer.DeserializationException)
                {
                    // try next option
                }
                catch (Exception)
                {
                    throw;
                }

                try
                {
                    return new CreateTransactionRequestBody(CreateTransactionRequestBodyType.InstantTransactionCreateRequest)
                    {
                        InstantTransactionCreateRequest = ResponseBodyDeserializer.DeserializeUndiscriminatedUnionMember<InstantTransactionCreateRequest>(json)
                    };
                }
                catch (ResponseBodyDeserializer.MissingMemberException)
                {
                    fallbackCandidates.Add((typeof(InstantTransactionCreateRequest), new CreateTransactionRequestBody(CreateTransactionRequestBodyType.InstantTransactionCreateRequest), "InstantTransactionCreateRequest"));
                }
                catch (ResponseBodyDeserializer.DeserializationException)
                {
                    // try next option
                }
                catch (Exception)
                {
                    throw;
                }

                if (fallbackCandidates.Count > 0)
                {
                    fallbackCandidates.Sort((a, b) => ResponseBodyDeserializer.CompareFallbackCandidates(a.Item1, b.Item1, json));
                    foreach(var (deserializationType, returnObject, propertyName) in fallbackCandidates)
                    {
                        try
                        {
                            return ResponseBodyDeserializer.DeserializeUndiscriminatedUnionFallback(deserializationType, returnObject, propertyName, json);
                        }
                        catch (ResponseBodyDeserializer.DeserializationException)
                        {
                            // try next fallback option
                        }
                        catch (Exception)
                        {
                            throw;
                        }
                    }
                }

                throw new InvalidOperationException("Could not deserialize into any supported types.");
            }

            public override void WriteJson(JsonWriter writer, object? value, JsonSerializer serializer)
            {
                if (value == null) {
                    writer.WriteRawValue("null");
                    return;
                }
                CreateTransactionRequestBody res = (CreateTransactionRequestBody)value;
                if (CreateTransactionRequestBodyType.FromString(res.Type).Equals(CreateTransactionRequestBodyType.Null))
                {
                    writer.WriteRawValue("null");
                    return;
                }
                if (res.TransactionCreateRequest != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.TransactionCreateRequest));
                    return;
                }
                if (res.InstantTransactionCreateRequest != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.InstantTransactionCreateRequest));
                    return;
                }

            }

        }

    }
}