//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Shippo.Models.Requests
{
    using Shippo.Models.Requests;
    using Shippo.Utils;
    
    public class ListCarrierParcelTemplatesRequest
    {

        /// <summary>
        /// filter by user or enabled
        /// </summary>
        [SpeakeasyMetadata("queryParam:style=form,explode=true,name=include")]
        public Include? Include { get; set; }

        /// <summary>
        /// filter by specific carrier
        /// </summary>
        [SpeakeasyMetadata("queryParam:style=form,explode=true,name=carrier")]
        public string? Carrier { get; set; }

        /// <summary>
        /// String used to pick a non-default API version to use
        /// </summary>
        [SpeakeasyMetadata("header:style=simple,explode=false,name=SHIPPO-API-VERSION")]
        public string? ShippoApiVersion { get; set; }
    }
}