//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Shippo.Models.Requests
{
    using Newtonsoft.Json.Linq;
    using Newtonsoft.Json;
    using Shippo.Models.Components;
    using Shippo.Utils;
    using System.Numerics;
    using System;
    

    public class RegisterCarrierAccountRequestBodyType
    {
        private RegisterCarrierAccountRequestBodyType(string value) { Value = value; }

        public string Value { get; private set; }
        public static RegisterCarrierAccountRequestBodyType CarrierAccountCanadaPostCreateRequest { get { return new RegisterCarrierAccountRequestBodyType("CarrierAccountCanadaPostCreateRequest"); } }
        
        public static RegisterCarrierAccountRequestBodyType CarrierAccountChronopostCreateRequest { get { return new RegisterCarrierAccountRequestBodyType("CarrierAccountChronopostCreateRequest"); } }
        
        public static RegisterCarrierAccountRequestBodyType CarrierAccountColissimoCreateRequest { get { return new RegisterCarrierAccountRequestBodyType("CarrierAccountColissimoCreateRequest"); } }
        
        public static RegisterCarrierAccountRequestBodyType CarrierAccountCorreosCreateRequest { get { return new RegisterCarrierAccountRequestBodyType("CarrierAccountCorreosCreateRequest"); } }
        
        public static RegisterCarrierAccountRequestBodyType CarrierAccountDeutschePostCreateRequest { get { return new RegisterCarrierAccountRequestBodyType("CarrierAccountDeutschePostCreateRequest"); } }
        
        public static RegisterCarrierAccountRequestBodyType CarrierAccountDHLExpressCreateRequest { get { return new RegisterCarrierAccountRequestBodyType("CarrierAccountDHLExpressCreateRequest"); } }
        
        public static RegisterCarrierAccountRequestBodyType CarrierAccountDpdDeCreateRequest { get { return new RegisterCarrierAccountRequestBodyType("CarrierAccountDpdDeCreateRequest"); } }
        
        public static RegisterCarrierAccountRequestBodyType CarrierAccountDPDUKCreateRequest { get { return new RegisterCarrierAccountRequestBodyType("CarrierAccountDPDUKCreateRequest"); } }
        
        public static RegisterCarrierAccountRequestBodyType CarrierAccountFedExCreateRequest { get { return new RegisterCarrierAccountRequestBodyType("CarrierAccountFedExCreateRequest"); } }
        
        public static RegisterCarrierAccountRequestBodyType CarrierAccountHermesUKCreateRequest { get { return new RegisterCarrierAccountRequestBodyType("CarrierAccountHermesUKCreateRequest"); } }
        
        public static RegisterCarrierAccountRequestBodyType CarrierAccountMondialRelayCreateRequest { get { return new RegisterCarrierAccountRequestBodyType("CarrierAccountMondialRelayCreateRequest"); } }
        
        public static RegisterCarrierAccountRequestBodyType CarrierAccountPosteItalianeCreateRequest { get { return new RegisterCarrierAccountRequestBodyType("CarrierAccountPosteItalianeCreateRequest"); } }
        
        public static RegisterCarrierAccountRequestBodyType CarrierAccountUPSCreateRequest { get { return new RegisterCarrierAccountRequestBodyType("CarrierAccountUPSCreateRequest"); } }
        
        public static RegisterCarrierAccountRequestBodyType CarrierAccountUSPSCreateRequest { get { return new RegisterCarrierAccountRequestBodyType("CarrierAccountUSPSCreateRequest"); } }
        
        public static RegisterCarrierAccountRequestBodyType Null { get { return new RegisterCarrierAccountRequestBodyType("null"); } }

        public override string ToString() { return Value; }
        public static implicit operator String(RegisterCarrierAccountRequestBodyType v) { return v.Value; }
        public static RegisterCarrierAccountRequestBodyType FromString(string v) {
            switch(v) {
                case "CarrierAccountCanadaPostCreateRequest": return CarrierAccountCanadaPostCreateRequest;
                case "CarrierAccountChronopostCreateRequest": return CarrierAccountChronopostCreateRequest;
                case "CarrierAccountColissimoCreateRequest": return CarrierAccountColissimoCreateRequest;
                case "CarrierAccountCorreosCreateRequest": return CarrierAccountCorreosCreateRequest;
                case "CarrierAccountDeutschePostCreateRequest": return CarrierAccountDeutschePostCreateRequest;
                case "CarrierAccountDHLExpressCreateRequest": return CarrierAccountDHLExpressCreateRequest;
                case "CarrierAccountDpdDeCreateRequest": return CarrierAccountDpdDeCreateRequest;
                case "CarrierAccountDPDUKCreateRequest": return CarrierAccountDPDUKCreateRequest;
                case "CarrierAccountFedExCreateRequest": return CarrierAccountFedExCreateRequest;
                case "CarrierAccountHermesUKCreateRequest": return CarrierAccountHermesUKCreateRequest;
                case "CarrierAccountMondialRelayCreateRequest": return CarrierAccountMondialRelayCreateRequest;
                case "CarrierAccountPosteItalianeCreateRequest": return CarrierAccountPosteItalianeCreateRequest;
                case "CarrierAccountUPSCreateRequest": return CarrierAccountUPSCreateRequest;
                case "CarrierAccountUSPSCreateRequest": return CarrierAccountUSPSCreateRequest;
                case "null": return Null;
                default: throw new ArgumentException("Invalid value for RegisterCarrierAccountRequestBodyType");
            }
        }
        public override bool Equals(object? obj)
        {
            if (obj == null || GetType() != obj.GetType())
            {
                return false;
            }
            return Value.Equals(((RegisterCarrierAccountRequestBodyType)obj).Value);
        }

        public override int GetHashCode()
        {
            return Value.GetHashCode();
        }
    }
    
/// <summary>
/// Examples.
/// </summary>
    [JsonConverter(typeof(RegisterCarrierAccountRequestBody.RegisterCarrierAccountRequestBodyConverter))]
    public class RegisterCarrierAccountRequestBody {
        public RegisterCarrierAccountRequestBody(RegisterCarrierAccountRequestBodyType type) {
            Type = type;
        }
        public CarrierAccountCanadaPostCreateRequest? CarrierAccountCanadaPostCreateRequest { get; set; } 
        public CarrierAccountChronopostCreateRequest? CarrierAccountChronopostCreateRequest { get; set; } 
        public CarrierAccountColissimoCreateRequest? CarrierAccountColissimoCreateRequest { get; set; } 
        public CarrierAccountCorreosCreateRequest? CarrierAccountCorreosCreateRequest { get; set; } 
        public CarrierAccountDeutschePostCreateRequest? CarrierAccountDeutschePostCreateRequest { get; set; } 
        public CarrierAccountDHLExpressCreateRequest? CarrierAccountDHLExpressCreateRequest { get; set; } 
        public CarrierAccountDpdDeCreateRequest? CarrierAccountDpdDeCreateRequest { get; set; } 
        public CarrierAccountDPDUKCreateRequest? CarrierAccountDPDUKCreateRequest { get; set; } 
        public CarrierAccountFedExCreateRequest? CarrierAccountFedExCreateRequest { get; set; } 
        public CarrierAccountHermesUKCreateRequest? CarrierAccountHermesUKCreateRequest { get; set; } 
        public CarrierAccountMondialRelayCreateRequest? CarrierAccountMondialRelayCreateRequest { get; set; } 
        public CarrierAccountPosteItalianeCreateRequest? CarrierAccountPosteItalianeCreateRequest { get; set; } 
        public CarrierAccountUPSCreateRequest? CarrierAccountUPSCreateRequest { get; set; } 
        public CarrierAccountUSPSCreateRequest? CarrierAccountUSPSCreateRequest { get; set; } 

        public RegisterCarrierAccountRequestBodyType Type { get; set; }


        public static RegisterCarrierAccountRequestBody CreateCarrierAccountCanadaPostCreateRequest(CarrierAccountCanadaPostCreateRequest carrierAccountCanadaPostCreateRequest) {
            RegisterCarrierAccountRequestBodyType typ = RegisterCarrierAccountRequestBodyType.CarrierAccountCanadaPostCreateRequest;

            RegisterCarrierAccountRequestBody res = new RegisterCarrierAccountRequestBody(typ);
            res.CarrierAccountCanadaPostCreateRequest = carrierAccountCanadaPostCreateRequest;
            return res;
        }

        public static RegisterCarrierAccountRequestBody CreateCarrierAccountChronopostCreateRequest(CarrierAccountChronopostCreateRequest carrierAccountChronopostCreateRequest) {
            RegisterCarrierAccountRequestBodyType typ = RegisterCarrierAccountRequestBodyType.CarrierAccountChronopostCreateRequest;

            RegisterCarrierAccountRequestBody res = new RegisterCarrierAccountRequestBody(typ);
            res.CarrierAccountChronopostCreateRequest = carrierAccountChronopostCreateRequest;
            return res;
        }

        public static RegisterCarrierAccountRequestBody CreateCarrierAccountColissimoCreateRequest(CarrierAccountColissimoCreateRequest carrierAccountColissimoCreateRequest) {
            RegisterCarrierAccountRequestBodyType typ = RegisterCarrierAccountRequestBodyType.CarrierAccountColissimoCreateRequest;

            RegisterCarrierAccountRequestBody res = new RegisterCarrierAccountRequestBody(typ);
            res.CarrierAccountColissimoCreateRequest = carrierAccountColissimoCreateRequest;
            return res;
        }

        public static RegisterCarrierAccountRequestBody CreateCarrierAccountCorreosCreateRequest(CarrierAccountCorreosCreateRequest carrierAccountCorreosCreateRequest) {
            RegisterCarrierAccountRequestBodyType typ = RegisterCarrierAccountRequestBodyType.CarrierAccountCorreosCreateRequest;

            RegisterCarrierAccountRequestBody res = new RegisterCarrierAccountRequestBody(typ);
            res.CarrierAccountCorreosCreateRequest = carrierAccountCorreosCreateRequest;
            return res;
        }

        public static RegisterCarrierAccountRequestBody CreateCarrierAccountDeutschePostCreateRequest(CarrierAccountDeutschePostCreateRequest carrierAccountDeutschePostCreateRequest) {
            RegisterCarrierAccountRequestBodyType typ = RegisterCarrierAccountRequestBodyType.CarrierAccountDeutschePostCreateRequest;

            RegisterCarrierAccountRequestBody res = new RegisterCarrierAccountRequestBody(typ);
            res.CarrierAccountDeutschePostCreateRequest = carrierAccountDeutschePostCreateRequest;
            return res;
        }

        public static RegisterCarrierAccountRequestBody CreateCarrierAccountDHLExpressCreateRequest(CarrierAccountDHLExpressCreateRequest carrierAccountDHLExpressCreateRequest) {
            RegisterCarrierAccountRequestBodyType typ = RegisterCarrierAccountRequestBodyType.CarrierAccountDHLExpressCreateRequest;

            RegisterCarrierAccountRequestBody res = new RegisterCarrierAccountRequestBody(typ);
            res.CarrierAccountDHLExpressCreateRequest = carrierAccountDHLExpressCreateRequest;
            return res;
        }

        public static RegisterCarrierAccountRequestBody CreateCarrierAccountDpdDeCreateRequest(CarrierAccountDpdDeCreateRequest carrierAccountDpdDeCreateRequest) {
            RegisterCarrierAccountRequestBodyType typ = RegisterCarrierAccountRequestBodyType.CarrierAccountDpdDeCreateRequest;

            RegisterCarrierAccountRequestBody res = new RegisterCarrierAccountRequestBody(typ);
            res.CarrierAccountDpdDeCreateRequest = carrierAccountDpdDeCreateRequest;
            return res;
        }

        public static RegisterCarrierAccountRequestBody CreateCarrierAccountDPDUKCreateRequest(CarrierAccountDPDUKCreateRequest carrierAccountDPDUKCreateRequest) {
            RegisterCarrierAccountRequestBodyType typ = RegisterCarrierAccountRequestBodyType.CarrierAccountDPDUKCreateRequest;

            RegisterCarrierAccountRequestBody res = new RegisterCarrierAccountRequestBody(typ);
            res.CarrierAccountDPDUKCreateRequest = carrierAccountDPDUKCreateRequest;
            return res;
        }

        public static RegisterCarrierAccountRequestBody CreateCarrierAccountFedExCreateRequest(CarrierAccountFedExCreateRequest carrierAccountFedExCreateRequest) {
            RegisterCarrierAccountRequestBodyType typ = RegisterCarrierAccountRequestBodyType.CarrierAccountFedExCreateRequest;

            RegisterCarrierAccountRequestBody res = new RegisterCarrierAccountRequestBody(typ);
            res.CarrierAccountFedExCreateRequest = carrierAccountFedExCreateRequest;
            return res;
        }

        public static RegisterCarrierAccountRequestBody CreateCarrierAccountHermesUKCreateRequest(CarrierAccountHermesUKCreateRequest carrierAccountHermesUKCreateRequest) {
            RegisterCarrierAccountRequestBodyType typ = RegisterCarrierAccountRequestBodyType.CarrierAccountHermesUKCreateRequest;

            RegisterCarrierAccountRequestBody res = new RegisterCarrierAccountRequestBody(typ);
            res.CarrierAccountHermesUKCreateRequest = carrierAccountHermesUKCreateRequest;
            return res;
        }

        public static RegisterCarrierAccountRequestBody CreateCarrierAccountMondialRelayCreateRequest(CarrierAccountMondialRelayCreateRequest carrierAccountMondialRelayCreateRequest) {
            RegisterCarrierAccountRequestBodyType typ = RegisterCarrierAccountRequestBodyType.CarrierAccountMondialRelayCreateRequest;

            RegisterCarrierAccountRequestBody res = new RegisterCarrierAccountRequestBody(typ);
            res.CarrierAccountMondialRelayCreateRequest = carrierAccountMondialRelayCreateRequest;
            return res;
        }

        public static RegisterCarrierAccountRequestBody CreateCarrierAccountPosteItalianeCreateRequest(CarrierAccountPosteItalianeCreateRequest carrierAccountPosteItalianeCreateRequest) {
            RegisterCarrierAccountRequestBodyType typ = RegisterCarrierAccountRequestBodyType.CarrierAccountPosteItalianeCreateRequest;

            RegisterCarrierAccountRequestBody res = new RegisterCarrierAccountRequestBody(typ);
            res.CarrierAccountPosteItalianeCreateRequest = carrierAccountPosteItalianeCreateRequest;
            return res;
        }

        public static RegisterCarrierAccountRequestBody CreateCarrierAccountUPSCreateRequest(CarrierAccountUPSCreateRequest carrierAccountUPSCreateRequest) {
            RegisterCarrierAccountRequestBodyType typ = RegisterCarrierAccountRequestBodyType.CarrierAccountUPSCreateRequest;

            RegisterCarrierAccountRequestBody res = new RegisterCarrierAccountRequestBody(typ);
            res.CarrierAccountUPSCreateRequest = carrierAccountUPSCreateRequest;
            return res;
        }

        public static RegisterCarrierAccountRequestBody CreateCarrierAccountUSPSCreateRequest(CarrierAccountUSPSCreateRequest carrierAccountUSPSCreateRequest) {
            RegisterCarrierAccountRequestBodyType typ = RegisterCarrierAccountRequestBodyType.CarrierAccountUSPSCreateRequest;

            RegisterCarrierAccountRequestBody res = new RegisterCarrierAccountRequestBody(typ);
            res.CarrierAccountUSPSCreateRequest = carrierAccountUSPSCreateRequest;
            return res;
        }

        public static RegisterCarrierAccountRequestBody CreateNull() {
            RegisterCarrierAccountRequestBodyType typ = RegisterCarrierAccountRequestBodyType.Null;
            return new RegisterCarrierAccountRequestBody(typ);
        }

        public class RegisterCarrierAccountRequestBodyConverter : JsonConverter
        {

            public override bool CanConvert(System.Type objectType) => objectType == typeof(RegisterCarrierAccountRequestBody);

            public override bool CanRead => true;

            public override object? ReadJson(JsonReader reader, System.Type objectType, object? existingValue, JsonSerializer serializer)
            { 
                var json = JRaw.Create(reader).ToString();

                if (json == "null") {
                    return null;
                }
                try
                {
                    CarrierAccountCanadaPostCreateRequest? carrierAccountCanadaPostCreateRequest = ResponseBodyDeserializer.Deserialize<CarrierAccountCanadaPostCreateRequest>(json, missingMemberHandling: MissingMemberHandling.Error);
                    return new RegisterCarrierAccountRequestBody(RegisterCarrierAccountRequestBodyType.CarrierAccountCanadaPostCreateRequest) {
                        CarrierAccountCanadaPostCreateRequest = carrierAccountCanadaPostCreateRequest
                    };
                }
                catch (Exception ex)
                {
                    if (!(ex is Newtonsoft.Json.JsonReaderException || ex is Newtonsoft.Json.JsonSerializationException)) {
                        throw ex;
                    }
                }
                try
                {
                    CarrierAccountChronopostCreateRequest? carrierAccountChronopostCreateRequest = ResponseBodyDeserializer.Deserialize<CarrierAccountChronopostCreateRequest>(json, missingMemberHandling: MissingMemberHandling.Error);
                    return new RegisterCarrierAccountRequestBody(RegisterCarrierAccountRequestBodyType.CarrierAccountChronopostCreateRequest) {
                        CarrierAccountChronopostCreateRequest = carrierAccountChronopostCreateRequest
                    };
                }
                catch (Exception ex)
                {
                    if (!(ex is Newtonsoft.Json.JsonReaderException || ex is Newtonsoft.Json.JsonSerializationException)) {
                        throw ex;
                    }
                }
                try
                {
                    CarrierAccountColissimoCreateRequest? carrierAccountColissimoCreateRequest = ResponseBodyDeserializer.Deserialize<CarrierAccountColissimoCreateRequest>(json, missingMemberHandling: MissingMemberHandling.Error);
                    return new RegisterCarrierAccountRequestBody(RegisterCarrierAccountRequestBodyType.CarrierAccountColissimoCreateRequest) {
                        CarrierAccountColissimoCreateRequest = carrierAccountColissimoCreateRequest
                    };
                }
                catch (Exception ex)
                {
                    if (!(ex is Newtonsoft.Json.JsonReaderException || ex is Newtonsoft.Json.JsonSerializationException)) {
                        throw ex;
                    }
                }
                try
                {
                    CarrierAccountCorreosCreateRequest? carrierAccountCorreosCreateRequest = ResponseBodyDeserializer.Deserialize<CarrierAccountCorreosCreateRequest>(json, missingMemberHandling: MissingMemberHandling.Error);
                    return new RegisterCarrierAccountRequestBody(RegisterCarrierAccountRequestBodyType.CarrierAccountCorreosCreateRequest) {
                        CarrierAccountCorreosCreateRequest = carrierAccountCorreosCreateRequest
                    };
                }
                catch (Exception ex)
                {
                    if (!(ex is Newtonsoft.Json.JsonReaderException || ex is Newtonsoft.Json.JsonSerializationException)) {
                        throw ex;
                    }
                }
                try
                {
                    CarrierAccountDeutschePostCreateRequest? carrierAccountDeutschePostCreateRequest = ResponseBodyDeserializer.Deserialize<CarrierAccountDeutschePostCreateRequest>(json, missingMemberHandling: MissingMemberHandling.Error);
                    return new RegisterCarrierAccountRequestBody(RegisterCarrierAccountRequestBodyType.CarrierAccountDeutschePostCreateRequest) {
                        CarrierAccountDeutschePostCreateRequest = carrierAccountDeutschePostCreateRequest
                    };
                }
                catch (Exception ex)
                {
                    if (!(ex is Newtonsoft.Json.JsonReaderException || ex is Newtonsoft.Json.JsonSerializationException)) {
                        throw ex;
                    }
                }
                try
                {
                    CarrierAccountDHLExpressCreateRequest? carrierAccountDHLExpressCreateRequest = ResponseBodyDeserializer.Deserialize<CarrierAccountDHLExpressCreateRequest>(json, missingMemberHandling: MissingMemberHandling.Error);
                    return new RegisterCarrierAccountRequestBody(RegisterCarrierAccountRequestBodyType.CarrierAccountDHLExpressCreateRequest) {
                        CarrierAccountDHLExpressCreateRequest = carrierAccountDHLExpressCreateRequest
                    };
                }
                catch (Exception ex)
                {
                    if (!(ex is Newtonsoft.Json.JsonReaderException || ex is Newtonsoft.Json.JsonSerializationException)) {
                        throw ex;
                    }
                }
                try
                {
                    CarrierAccountDpdDeCreateRequest? carrierAccountDpdDeCreateRequest = ResponseBodyDeserializer.Deserialize<CarrierAccountDpdDeCreateRequest>(json, missingMemberHandling: MissingMemberHandling.Error);
                    return new RegisterCarrierAccountRequestBody(RegisterCarrierAccountRequestBodyType.CarrierAccountDpdDeCreateRequest) {
                        CarrierAccountDpdDeCreateRequest = carrierAccountDpdDeCreateRequest
                    };
                }
                catch (Exception ex)
                {
                    if (!(ex is Newtonsoft.Json.JsonReaderException || ex is Newtonsoft.Json.JsonSerializationException)) {
                        throw ex;
                    }
                }
                try
                {
                    CarrierAccountDPDUKCreateRequest? carrierAccountDPDUKCreateRequest = ResponseBodyDeserializer.Deserialize<CarrierAccountDPDUKCreateRequest>(json, missingMemberHandling: MissingMemberHandling.Error);
                    return new RegisterCarrierAccountRequestBody(RegisterCarrierAccountRequestBodyType.CarrierAccountDPDUKCreateRequest) {
                        CarrierAccountDPDUKCreateRequest = carrierAccountDPDUKCreateRequest
                    };
                }
                catch (Exception ex)
                {
                    if (!(ex is Newtonsoft.Json.JsonReaderException || ex is Newtonsoft.Json.JsonSerializationException)) {
                        throw ex;
                    }
                }
                try
                {
                    CarrierAccountFedExCreateRequest? carrierAccountFedExCreateRequest = ResponseBodyDeserializer.Deserialize<CarrierAccountFedExCreateRequest>(json, missingMemberHandling: MissingMemberHandling.Error);
                    return new RegisterCarrierAccountRequestBody(RegisterCarrierAccountRequestBodyType.CarrierAccountFedExCreateRequest) {
                        CarrierAccountFedExCreateRequest = carrierAccountFedExCreateRequest
                    };
                }
                catch (Exception ex)
                {
                    if (!(ex is Newtonsoft.Json.JsonReaderException || ex is Newtonsoft.Json.JsonSerializationException)) {
                        throw ex;
                    }
                }
                try
                {
                    CarrierAccountHermesUKCreateRequest? carrierAccountHermesUKCreateRequest = ResponseBodyDeserializer.Deserialize<CarrierAccountHermesUKCreateRequest>(json, missingMemberHandling: MissingMemberHandling.Error);
                    return new RegisterCarrierAccountRequestBody(RegisterCarrierAccountRequestBodyType.CarrierAccountHermesUKCreateRequest) {
                        CarrierAccountHermesUKCreateRequest = carrierAccountHermesUKCreateRequest
                    };
                }
                catch (Exception ex)
                {
                    if (!(ex is Newtonsoft.Json.JsonReaderException || ex is Newtonsoft.Json.JsonSerializationException)) {
                        throw ex;
                    }
                }
                try
                {
                    CarrierAccountMondialRelayCreateRequest? carrierAccountMondialRelayCreateRequest = ResponseBodyDeserializer.Deserialize<CarrierAccountMondialRelayCreateRequest>(json, missingMemberHandling: MissingMemberHandling.Error);
                    return new RegisterCarrierAccountRequestBody(RegisterCarrierAccountRequestBodyType.CarrierAccountMondialRelayCreateRequest) {
                        CarrierAccountMondialRelayCreateRequest = carrierAccountMondialRelayCreateRequest
                    };
                }
                catch (Exception ex)
                {
                    if (!(ex is Newtonsoft.Json.JsonReaderException || ex is Newtonsoft.Json.JsonSerializationException)) {
                        throw ex;
                    }
                }
                try
                {
                    CarrierAccountPosteItalianeCreateRequest? carrierAccountPosteItalianeCreateRequest = ResponseBodyDeserializer.Deserialize<CarrierAccountPosteItalianeCreateRequest>(json, missingMemberHandling: MissingMemberHandling.Error);
                    return new RegisterCarrierAccountRequestBody(RegisterCarrierAccountRequestBodyType.CarrierAccountPosteItalianeCreateRequest) {
                        CarrierAccountPosteItalianeCreateRequest = carrierAccountPosteItalianeCreateRequest
                    };
                }
                catch (Exception ex)
                {
                    if (!(ex is Newtonsoft.Json.JsonReaderException || ex is Newtonsoft.Json.JsonSerializationException)) {
                        throw ex;
                    }
                }
                try
                {
                    CarrierAccountUPSCreateRequest? carrierAccountUPSCreateRequest = ResponseBodyDeserializer.Deserialize<CarrierAccountUPSCreateRequest>(json, missingMemberHandling: MissingMemberHandling.Error);
                    return new RegisterCarrierAccountRequestBody(RegisterCarrierAccountRequestBodyType.CarrierAccountUPSCreateRequest) {
                        CarrierAccountUPSCreateRequest = carrierAccountUPSCreateRequest
                    };
                }
                catch (Exception ex)
                {
                    if (!(ex is Newtonsoft.Json.JsonReaderException || ex is Newtonsoft.Json.JsonSerializationException)) {
                        throw ex;
                    }
                }
                try
                {
                    CarrierAccountUSPSCreateRequest? carrierAccountUSPSCreateRequest = ResponseBodyDeserializer.Deserialize<CarrierAccountUSPSCreateRequest>(json, missingMemberHandling: MissingMemberHandling.Error);
                    return new RegisterCarrierAccountRequestBody(RegisterCarrierAccountRequestBodyType.CarrierAccountUSPSCreateRequest) {
                        CarrierAccountUSPSCreateRequest = carrierAccountUSPSCreateRequest
                    };
                }
                catch (Exception ex)
                {
                    if (!(ex is Newtonsoft.Json.JsonReaderException || ex is Newtonsoft.Json.JsonSerializationException)) {
                        throw ex;
                    }
                }

                throw new InvalidOperationException("Could not deserialize into any supported types.");
            }

            public override void WriteJson(JsonWriter writer, object? value, JsonSerializer serializer)
            {
                if (value == null) {
                    writer.WriteRawValue("null");
                    return;
                }
                RegisterCarrierAccountRequestBody res = (RegisterCarrierAccountRequestBody)value;
                if (RegisterCarrierAccountRequestBodyType.FromString(res.Type).Equals(RegisterCarrierAccountRequestBodyType.Null))
                {
                    writer.WriteRawValue("null");
                    return;
                }
                if (res.CarrierAccountCanadaPostCreateRequest != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.CarrierAccountCanadaPostCreateRequest));
                    return;
                }
                if (res.CarrierAccountChronopostCreateRequest != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.CarrierAccountChronopostCreateRequest));
                    return;
                }
                if (res.CarrierAccountColissimoCreateRequest != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.CarrierAccountColissimoCreateRequest));
                    return;
                }
                if (res.CarrierAccountCorreosCreateRequest != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.CarrierAccountCorreosCreateRequest));
                    return;
                }
                if (res.CarrierAccountDeutschePostCreateRequest != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.CarrierAccountDeutschePostCreateRequest));
                    return;
                }
                if (res.CarrierAccountDHLExpressCreateRequest != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.CarrierAccountDHLExpressCreateRequest));
                    return;
                }
                if (res.CarrierAccountDpdDeCreateRequest != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.CarrierAccountDpdDeCreateRequest));
                    return;
                }
                if (res.CarrierAccountDPDUKCreateRequest != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.CarrierAccountDPDUKCreateRequest));
                    return;
                }
                if (res.CarrierAccountFedExCreateRequest != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.CarrierAccountFedExCreateRequest));
                    return;
                }
                if (res.CarrierAccountHermesUKCreateRequest != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.CarrierAccountHermesUKCreateRequest));
                    return;
                }
                if (res.CarrierAccountMondialRelayCreateRequest != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.CarrierAccountMondialRelayCreateRequest));
                    return;
                }
                if (res.CarrierAccountPosteItalianeCreateRequest != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.CarrierAccountPosteItalianeCreateRequest));
                    return;
                }
                if (res.CarrierAccountUPSCreateRequest != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.CarrierAccountUPSCreateRequest));
                    return;
                }
                if (res.CarrierAccountUSPSCreateRequest != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.CarrierAccountUSPSCreateRequest));
                    return;
                }

            }
        }

    }

}