//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Shippo
{
    using Newtonsoft.Json;
    using Shippo.Hooks;
    using Shippo.Models.Components;
    using Shippo.Models.Errors;
    using Shippo.Utils;
    using Shippo.Utils.Retries;
    using System;
    using System.Collections.Generic;
    using System.Net.Http;
    using System.Threading.Tasks;
    /// <summary>
    /// Shippo external API.: Use this API to integrate with the Shippo service.
    /// </summary>
    public interface IShippoSDK
    {
        /// <summary>
        /// Addresses are the locations a parcel is being shipped **from** and **to**. They represent company and residential places. Among other things, you can use address objects to create shipments, calculate shipping rates, and purchase shipping labels.
        /// </summary>
        public IAddresses Addresses { get; }

        /// <summary>
        /// A batch is a technique for creating multiple labels at once. Use the  batch object to create and purchase many shipments in two API calls. After creating the batch, retrieve the batch to verify that all shipments are valid. You can add and remove shipments after you have created the batch. When all shipments are valid you can purchase the batch and retrieve all the shipping labels.
        /// </summary>
        public IBatches Batches { get; }

        /// <summary>
        /// Carriers are the companies who deliver your package. Shippo uses Carrier account objects as credentials to retrieve shipping rates and purchase labels from shipping Carriers.
        /// </summary>
        public ICarrierAccounts CarrierAccounts { get; }

        /// <summary>
        /// Customs declarations are relevant information, including one or multiple customs items, you need to provide for <br/>
        /// customs clearance for your international shipments.
        /// </summary>
        public ICustomsDeclarations CustomsDeclarations { get; }

        /// <summary>
        /// Customs declarations are relevant information, including one or multiple customs items, you need to provide for customs clearance for your international shipments.
        /// </summary>
        public ICustomsItems CustomsItems { get; }

        /// <summary>
        /// Rates at checkout is a tool for merchants to display up-to-date shipping estimates based on what's in their customers cart and where they’re shipping to.<br/>
        /// Merchants set up curated shipping options for customers in the checkout flow based on data in the shopping cart. The request must include the **to** address and item information. Optional fields are the **from** address and package information. If the optional fields are not included, the service will use the default address and/or package configured for rates at checkout. The response is a list of shipping options based on the Service Group configuration.<br/>
        /// (see <a href="/shippoapi/public-api/service-groups">Service Group configuration</a> for details).<br/>
        /// <br/>
        /// <br/>
        /// <br/>
        /// # Default Parcel Template<br/>
        /// Assign one of your user parcel templates to be the default used when generating Live Rates. This template will be used by default when generating Live Rates, unless you explicitly provide a parcel in the Live Rates request.
        /// </summary>
        public IRatesAtCheckout RatesAtCheckout { get; }

        /// <summary>
        /// A manifest is a single-page document with a barcode that carriers can scan to accept all packages into transit without the need to scan each item individually.<br/>
        /// They are close-outs of shipping labels of a certain day. Some carriers require manifests to  process the shipments.
        /// </summary>
        public IManifests Manifests { get; }

        /// <summary>
        /// An order is a request from a customer to purchase goods from a merchant.<br/>
        /// Use the orders object to load orders from your system to the Shippo dashboard.<br/>
        /// You can use the orders object to create, retrieve, list, and manage orders programmatically.<br/>
        /// You can also retrieve shipping rates, purchase labels, and track shipments for each order.
        /// </summary>
        public IOrders Orders { get; }

        /// <summary>
        /// A carrier parcel template represents a package used for shipping that has preset dimensions defined by a carrier. Some examples of a carrier parcel template include USPS Flat Rate Box and Fedex Small Pak. When using a carrier parcel template, the rates returned may be limited to the carrier that provides the box. You can create user parcel templates using a carrier parcel template. Shippo takes the dimensions of the carrier parcel template but you must configure the weight.
        /// </summary>
        public ICarrierParcelTemplates CarrierParcelTemplates { get; }

        /// <summary>
        /// A parcel is an item you are shipping. The parcel object includes details about its physical make-up of the parcel. It includes dimensions and weight that Shippo uses to calculate rates.
        /// </summary>
        public IParcels Parcels { get; }

        /// <summary>
        /// A pickup is when you schedule a carrier to collect a package for delivery.<br/>
        /// Use Shippo’s pickups endpoint to schedule pickups with USPS and DHL Express for eligible shipments that you have already created.
        /// </summary>
        public IPickups Pickups { get; }

        /// <summary>
        /// A rate is the cost to ship a parcel from a carrier. The rate object details the service level including the cost and transit time.
        /// </summary>
        public IRates Rates { get; }

        /// <summary>
        /// Refunds are reimbursements for successfully created but unused shipping labels or other charges.
        /// </summary>
        public IRefunds Refunds { get; }

        /// <summary>
        /// A service group is a set of service levels grouped together. <br/>
        /// Rates at checkout uses services groups to present available shipping options to customers in their shopping basket.
        /// </summary>
        public IServiceGroups ServiceGroups { get; }

        /// <summary>
        /// A shipment is the act of transporting goods. A shipment object contains **to** and **from** addresses, and the parcel details that you are shipping. You can use the shipment object to retrieve shipping rates and purchase a shipping label.
        /// </summary>
        public IShipments Shipments { get; }

        /// <summary>
        /// &lt;p style="text-align: center; background-color: #F2F3F4;"&gt;&lt;/br&gt;<br/>
        /// If you purchased your shipping label through Shippo, you can also get all the tracking details of your Shipment <br/>
        /// from the <a href="/shippoapi/public-api/transactions">Transaction</a> object.<br/>
        /// &lt;/br&gt;&lt;/br&gt;&lt;/p&gt;<br/>
        /// A tracking status of a package is an indication of current location of a package in the supply chain. For example,  sorting, warehousing, or out for delivery. Use the tracking status object to track the location of your shipments.<br/>
        /// <br/>
        /// When using your <a href="https://docs.goshippo.com/docs/guides_general/authentication/">Test</a> token for tracking, you need to use Shippo's <br/>
        /// predefined tokens for testing different tracking statuses. You can find more information in our <br/>
        /// <a href="https://docs.goshippo.com/docs/tracking/tracking/">Tracking tutorial</a> on how to do this, and what the <br/>
        /// payloads look like.
        /// </summary>
        public ITrackingStatus TrackingStatus { get; }

        /// <summary>
        /// A transaction is the purchase of a shipping label from a shipping provider for a specific service. You can print purchased labels and used them to ship a parcel with a carrier, such as USPS or FedEx.
        /// </summary>
        public ITransactions Transactions { get; }

        /// <summary>
        /// A user parcel template represents a package used for shipping that has preset dimensions and attributes defined <br/>
        /// by you. They are useful for capturing attributes of parcel-types you frequently use for shipping, allowing <br/>
        /// them to be defined once and then used for many shipments. These parcel templates can also be used for live rates.<br/>
        /// <br/>
        /// User parcel templates can also be created using a carrier parcel template, where the dimensions will be copied from <br/>
        /// the carrier presets, but the weight can be configured by you.
        /// </summary>
        public IUserParcelTemplates UserParcelTemplates { get; }

        /// <summary>
        /// Shippo Accounts are used by Shippo Platform Accounts to create and manage Managed Shippo Accounts. <br/>
        /// Managed Shippo Accounts are headless accounts that represent your customers. They are opaque to your end customers, meaning customers do not need to create their own Shippo login or have a billing relationship with Shippo. <br/>
        /// They can be used by marketplaces, e-commerce platforms, and third-party logistics providers who want to offer, seamless, built-in shipping functionality to their customers. See our <a href="https://docs.goshippo.com/docs/platformaccounts/platform_accounts/">guide</a> for more details.
        /// </summary>
        public IShippoAccounts ShippoAccounts { get; }

        /// <summary>
        /// Webhooks are a way for Shippo to notify your application when a specific event occurs. For example, when a label is purchased or when a shipment tracking status has changed. You can use webhooks to trigger actions in your application, such as sending an email or updating a database.
        /// </summary>
        public IWebhooks Webhooks { get; }
    }

    /// <summary>
    /// Shippo external API.: Use this API to integrate with the Shippo service.
    /// </summary>
    public class ShippoSDK: IShippoSDK
    {
        /// <summary>
        /// The main SDK Configuration.
        /// </summary>
        public SDKConfig SDKConfiguration { get; private set; }
        /// <summary>
        /// The Addresses sub-SDK.
        /// </summary>
        public IAddresses Addresses { get; private set; }
        /// <summary>
        /// The Batches sub-SDK.
        /// </summary>
        public IBatches Batches { get; private set; }
        /// <summary>
        /// The CarrierAccounts sub-SDK.
        /// </summary>
        public ICarrierAccounts CarrierAccounts { get; private set; }
        /// <summary>
        /// The CustomsDeclarations sub-SDK.
        /// </summary>
        public ICustomsDeclarations CustomsDeclarations { get; private set; }
        /// <summary>
        /// The CustomsItems sub-SDK.
        /// </summary>
        public ICustomsItems CustomsItems { get; private set; }
        /// <summary>
        /// The RatesAtCheckout sub-SDK.
        /// </summary>
        public IRatesAtCheckout RatesAtCheckout { get; private set; }
        /// <summary>
        /// The Manifests sub-SDK.
        /// </summary>
        public IManifests Manifests { get; private set; }
        /// <summary>
        /// The Orders sub-SDK.
        /// </summary>
        public IOrders Orders { get; private set; }
        /// <summary>
        /// The CarrierParcelTemplates sub-SDK.
        /// </summary>
        public ICarrierParcelTemplates CarrierParcelTemplates { get; private set; }
        /// <summary>
        /// The Parcels sub-SDK.
        /// </summary>
        public IParcels Parcels { get; private set; }
        /// <summary>
        /// The Pickups sub-SDK.
        /// </summary>
        public IPickups Pickups { get; private set; }
        /// <summary>
        /// The Rates sub-SDK.
        /// </summary>
        public IRates Rates { get; private set; }
        /// <summary>
        /// The Refunds sub-SDK.
        /// </summary>
        public IRefunds Refunds { get; private set; }
        /// <summary>
        /// The ServiceGroups sub-SDK.
        /// </summary>
        public IServiceGroups ServiceGroups { get; private set; }
        /// <summary>
        /// The Shipments sub-SDK.
        /// </summary>
        public IShipments Shipments { get; private set; }
        /// <summary>
        /// The TrackingStatus sub-SDK.
        /// </summary>
        public ITrackingStatus TrackingStatus { get; private set; }
        /// <summary>
        /// The Transactions sub-SDK.
        /// </summary>
        public ITransactions Transactions { get; private set; }
        /// <summary>
        /// The UserParcelTemplates sub-SDK.
        /// </summary>
        public IUserParcelTemplates UserParcelTemplates { get; private set; }
        /// <summary>
        /// The ShippoAccounts sub-SDK.
        /// </summary>
        public IShippoAccounts ShippoAccounts { get; private set; }
        /// <summary>
        /// The Webhooks sub-SDK.
        /// </summary>
        public IWebhooks Webhooks { get; private set; }

        /// <summary>
        /// Initializes a new instance of the SDK based on a <see cref="SDKConfig"/> configuration object.
        /// </summary>
        /// <param name="config">The SDK configuration object.</param>
        public ShippoSDK(SDKConfig config)
        {
            SDKConfiguration = config;
            InitHooks();

            Addresses = new Addresses(SDKConfiguration);

            Batches = new Batches(SDKConfiguration);

            CarrierAccounts = new CarrierAccounts(SDKConfiguration);

            CustomsDeclarations = new CustomsDeclarations(SDKConfiguration);

            CustomsItems = new CustomsItems(SDKConfiguration);

            RatesAtCheckout = new RatesAtCheckout(SDKConfiguration);

            Manifests = new Manifests(SDKConfiguration);

            Orders = new Orders(SDKConfiguration);

            CarrierParcelTemplates = new CarrierParcelTemplates(SDKConfiguration);

            Parcels = new Parcels(SDKConfiguration);

            Pickups = new Pickups(SDKConfiguration);

            Rates = new Rates(SDKConfiguration);

            Refunds = new Refunds(SDKConfiguration);

            ServiceGroups = new ServiceGroups(SDKConfiguration);

            Shipments = new Shipments(SDKConfiguration);

            TrackingStatus = new TrackingStatus(SDKConfiguration);

            Transactions = new Transactions(SDKConfiguration);

            UserParcelTemplates = new UserParcelTemplates(SDKConfiguration);

            ShippoAccounts = new ShippoAccounts(SDKConfiguration);

            Webhooks = new Webhooks(SDKConfiguration);
        }

        /// <summary>
        /// Initializes a new instance of the SDK with optional configuration parameters.
        /// </summary>
        /// <param name="apiKeyHeader">The security configuration to use for API requests. If provided, this will be used as a static security configuration.</param>
        /// <param name="apiKeyHeaderSource">A function that returns the security configuration dynamically. This takes precedence over the static security parameter if both are provided.</param>
        /// <param name="shippoApiVersion">Optional string used to pick a non-default API version to use. See our <a href="https://docs.goshippo.com/docs/api_concepts/apiversioning/">API version</a> guide.</param>
        /// <param name="serverIndex">The index of the server to use from the predefined server list. Must be between 0 and the length of the server list. Defaults to 0 if not specified.</param>
        /// <param name="serverUrl">A custom server URL to use instead of the predefined server list. If provided with urlParams, the URL will be templated with the provided parameters.</param>
        /// <param name="urlParams">A dictionary of parameters to use for templating the serverUrl. Only used when serverUrl is provided.</param>
        /// <param name="client">A custom HTTP client implementation to use for making API requests. If not provided, the default SpeakeasyHttpClient will be used.</param>
        /// <param name="retryConfig">Configuration for retry behavior when API requests fail. Defines retry strategies, backoff policies, and maximum retry attempts.</param>
        /// <exception cref="ArgumentOutOfRangeException">Invalid value provided for <paramref name="serverIndex"/>: must be between 0 (inclusive) and 1 (exclusive).</exception>
        /// <exception cref="ArgumentException">None of <paramref name="apiKeyHeader"/> and <paramref name="apiKeyHeaderSource"/> were provided.</exception>
        public ShippoSDK(
            string? apiKeyHeader = null,
            Func<string>? apiKeyHeaderSource = null,
            string? shippoApiVersion = null,
            int? serverIndex = null,
            string? serverUrl = null,
            Dictionary<string, string>? urlParams = null,
            ISpeakeasyHttpClient? client = null,
            RetryConfig? retryConfig = null
        )
        {
            if (serverIndex != null)
            {
                if (serverIndex.Value < 0 || serverIndex.Value >= SDKConfig.ServerList.Length)
                {
                    throw new ArgumentOutOfRangeException($"Invalid server index {serverIndex}: must be between 0 (inclusive) and {SDKConfig.ServerList.Length} (exclusive)." );
                }
            }

            if (serverUrl != null)
            {
                if (urlParams != null)
                {
                    serverUrl = Utilities.TemplateUrl(serverUrl, urlParams);
                }
            }
            Func<Shippo.Models.Components.Security>? _securitySource = null;

            if(apiKeyHeaderSource != null)
            {
                _securitySource = () => new Shippo.Models.Components.Security() { APIKeyHeader = apiKeyHeaderSource() };
            }
            else if(apiKeyHeader != null)
            {
                _securitySource = () => new Shippo.Models.Components.Security() { APIKeyHeader = apiKeyHeader };
            }
            else
            {
                throw new ArgumentException("apiKeyHeader and apiKeyHeaderSource cannot both be null");
            }

            SDKConfiguration = new SDKConfig(client)
            {
                ShippoApiVersion = shippoApiVersion,
                ServerIndex = serverIndex == null ? 0 : serverIndex.Value,
                ServerUrl = serverUrl == null ? "" : serverUrl,
                SecuritySource = _securitySource,
                RetryConfig = retryConfig
            };

            InitHooks();

            Addresses = new Addresses(SDKConfiguration);

            Batches = new Batches(SDKConfiguration);

            CarrierAccounts = new CarrierAccounts(SDKConfiguration);

            CustomsDeclarations = new CustomsDeclarations(SDKConfiguration);

            CustomsItems = new CustomsItems(SDKConfiguration);

            RatesAtCheckout = new RatesAtCheckout(SDKConfiguration);

            Manifests = new Manifests(SDKConfiguration);

            Orders = new Orders(SDKConfiguration);

            CarrierParcelTemplates = new CarrierParcelTemplates(SDKConfiguration);

            Parcels = new Parcels(SDKConfiguration);

            Pickups = new Pickups(SDKConfiguration);

            Rates = new Rates(SDKConfiguration);

            Refunds = new Refunds(SDKConfiguration);

            ServiceGroups = new ServiceGroups(SDKConfiguration);

            Shipments = new Shipments(SDKConfiguration);

            TrackingStatus = new TrackingStatus(SDKConfiguration);

            Transactions = new Transactions(SDKConfiguration);

            UserParcelTemplates = new UserParcelTemplates(SDKConfiguration);

            ShippoAccounts = new ShippoAccounts(SDKConfiguration);

            Webhooks = new Webhooks(SDKConfiguration);
        }

        private void InitHooks()
        {
            string preHooksUrl = SDKConfiguration.GetTemplatedServerUrl();
            var (postHooksUrl, postHooksClient) = SDKConfiguration.Hooks.SDKInit(preHooksUrl, SDKConfiguration.Client);
            var config = SDKConfiguration;
            if (preHooksUrl != postHooksUrl)
            {
                config.ServerUrl = postHooksUrl;
            }
            config.Client = postHooksClient;
            SDKConfiguration = config;
        }

        /// <summary>
        /// Builder class for constructing an instance of the SDK.
        /// </summary>
        public class SDKBuilder
        {
            private SDKConfig _sdkConfig = new SDKConfig(client: new SpeakeasyHttpClient());

            public SDKBuilder() { }

            /// <summary>
            /// Overrides the default server by index.
            /// </summary>
            public SDKBuilder WithServerIndex(int serverIndex)
            {
                if (serverIndex < 0 || serverIndex >= SDKConfig.ServerList.Length)
                {
                    throw new ArgumentOutOfRangeException($"Invalid server index {serverIndex}: must be between 0 (inclusive) and {SDKConfig.ServerList.Length} (exclusive)." );
                }
                _sdkConfig.ServerIndex = serverIndex;
                return this;
            }

            /// <summary>
            /// Overrides the default server URL for the SDK.
            /// </summary>
            public SDKBuilder WithServerUrl(string serverUrl, Dictionary<string, string>? serverVariables = null)
            {
                if (serverVariables != null)
                {
                    serverUrl = Utilities.TemplateUrl(serverUrl, serverVariables);
                }
                _sdkConfig.ServerUrl = serverUrl;
                return this;
            }
            /// <summary>
            /// Sets the ShippoApiVersion global parameter for the SDK.
            /// </summary>
            public SDKBuilder WithShippoApiVersion(string shippoApiVersion)
            {
                _sdkConfig.ShippoApiVersion = shippoApiVersion;
                return this;
            }

            /// <summary>
            /// Sets the apiKeyHeaderSource security parameter for the SDK.
            /// </summary>
            public SDKBuilder WithApiKeyHeaderSource(Func<string> apiKeyHeaderSource)
            {
                _sdkConfig.SecuritySource = () => new Shippo.Models.Components.Security() { APIKeyHeader = apiKeyHeaderSource() };
                return this;
            }

            /// <summary>
            /// Sets the apiKeyHeader security parameter for the SDK.
            /// </summary>
            public SDKBuilder WithApiKeyHeader(string apiKeyHeader)
            {
                _sdkConfig.SecuritySource = () => new Shippo.Models.Components.Security() { APIKeyHeader = apiKeyHeader };
                return this;
            }

            /// <summary>
            /// Sets a custom HTTP client to be used by the SDK.
            /// </summary>
            public SDKBuilder WithClient(ISpeakeasyHttpClient client)
            {
                _sdkConfig.Client = client;
                return this;
            }

            /// <summary>
            /// Sets the retry configuration for the SDK.
            /// </summary>
            public SDKBuilder WithRetryConfig(RetryConfig retryConfig)
            {
                _sdkConfig.RetryConfig = retryConfig;
                return this;
            }

            /// <summary>
            /// Builds and returns the SDK instance.
            /// </summary>
            public ShippoSDK Build()
            {
              if (_sdkConfig.SecuritySource == null) {
                  throw new ArgumentException("securitySource cannot be null. One of `ApiKeyHeader` or `apiKeyHeaderSource` needs to be defined.");
              }
              return new ShippoSDK(_sdkConfig);
            }

        }

        public static SDKBuilder Builder() => new SDKBuilder();
    }
}