//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Shippo.Models.Components
{
    using Newtonsoft.Json;
    using Shippo.Models.Components;
    using Shippo.Utils;
    using System.Collections.Generic;
    
    /// <summary>
    /// Object that contains information regarding if an address had been validated or not. Also contains any messages <br/>
    /// 
    /// <remarks>
    /// generated during validation. Children keys are &lt;code&gt;is_valid&lt;/code&gt;(boolean) and &lt;code&gt;messages&lt;/code&gt;(array).
    /// </remarks>
    /// </summary>
    public class AddressValidationResults
    {

        [JsonProperty("is_valid")]
        public bool? IsValid { get; set; }

        [JsonProperty("messages")]
        public List<AddressValidationResultsMessage>? Messages { get; set; }
    }
}