//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Shippo.Models.Components
{
    using Newtonsoft.Json;
    using Shippo.Models.Components;
    using Shippo.Utils;
    using System.Collections.Generic;

    /// <summary>
    /// The batch shipment object is a wrapper around a shipment object, which include shipment-specific information<br/>
    /// for batch processing.<br/>
    /// <br/>
    /// Note: batch shipments can only be created on the batch endpoint, either when creating a batch object or by through<br/>
    /// the `/batches/{BATCH_OBJECT_ID}/add_shipments` endpoint.
    /// </summary>
    public class BatchShipment
    {
        /// <summary>
        /// Object ID of the carrier account to be used for this shipment (will override batch default).
        /// </summary>
        [JsonProperty("carrier_account")]
        public string? CarrierAccount { get; set; }

        /// <summary>
        /// A string of up to 100 characters that can be filled with any additional information you want <br/>
        /// to attach to the object.
        /// </summary>
        [JsonProperty("metadata")]
        public string? Metadata { get; set; }

        /// <summary>
        /// A token that sets the shipping method for the batch, overriding the batch default. <br/>
        /// Servicelevel tokens can be found <a href="/shippoapi/public-api/service-levels">in this list</a> <br/>
        /// or <a href="/shippoapi/public-api/carrier-accounts/listcarrieraccounts">at this endpoint</a>.
        /// </summary>
        [JsonProperty("servicelevel_token")]
        public string? ServicelevelToken { get; set; }

        /// <summary>
        /// List of Shipment and Transaction error messages.
        /// </summary>
        [JsonProperty("messages")]
        public List<object>? Messages { get; set; }

        /// <summary>
        /// Object ID of this batch shipment. Can be used in the remove_shipments endpoint.
        /// </summary>
        [JsonProperty("object_id")]
        public string ObjectId { get; set; } = default!;

        /// <summary>
        /// Object ID of the shipment object created for this batch shipment.
        /// </summary>
        [JsonProperty("shipment")]
        public string Shipment { get; set; } = default!;

        /// <summary>
        /// `INVALID` batch shipments cannot be purchased and will have to be removed, fixed, and added to the batch again.&lt;br&gt;<br/>
        /// `VALID` batch shipments can be purchased. &lt;br&gt;<br/>
        /// Batch shipments with the status `TRANSACTION_FAILED` were not able to be purchased and the error will be displayed on the message field&lt;br&gt; <br/>
        /// `INCOMPLETE` batch shipments have an issue with the Address and will need to be removed, fixed, and added to the batch again.
        /// </summary>
        [JsonProperty("status")]
        public Status Status { get; set; } = default!;

        /// <summary>
        /// Object ID of the transaction object created for this batch shipment.
        /// </summary>
        [JsonProperty("transaction")]
        public string? Transaction { get; set; }
    }
}