//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Shippo.Models.Components
{
    using Newtonsoft.Json;
    using Newtonsoft.Json.Linq;
    using Shippo.Models.Components;
    using Shippo.Utils;
    using System;
    using System.Collections.Generic;
    using System.Numerics;
    using System.Reflection;

    public class CarrierAccountParametersType
    {
        private CarrierAccountParametersType(string value) { Value = value; }

        public string Value { get; private set; }

        public static CarrierAccountParametersType MapOfAny { get { return new CarrierAccountParametersType("mapOfAny"); } }

        public static CarrierAccountParametersType FedExConnectExistingOwnAccountParameters { get { return new CarrierAccountParametersType("FedExConnectExistingOwnAccountParameters"); } }

        public static CarrierAccountParametersType UPSConnectExistingOwnAccountParameters { get { return new CarrierAccountParametersType("UPSConnectExistingOwnAccountParameters"); } }

        public override string ToString() { return Value; }
        public static implicit operator String(CarrierAccountParametersType v) { return v.Value; }
        public static CarrierAccountParametersType FromString(string v) {
            switch(v) {
                case "mapOfAny": return MapOfAny;
                case "FedExConnectExistingOwnAccountParameters": return FedExConnectExistingOwnAccountParameters;
                case "UPSConnectExistingOwnAccountParameters": return UPSConnectExistingOwnAccountParameters;
                default: throw new ArgumentException("Invalid value for CarrierAccountParametersType");
            }
        }
        public override bool Equals(object? obj)
        {
            if (obj == null || GetType() != obj.GetType())
            {
                return false;
            }
            return Value.Equals(((CarrierAccountParametersType)obj).Value);
        }

        public override int GetHashCode()
        {
            return Value.GetHashCode();
        }
    }

    [JsonConverter(typeof(CarrierAccountParameters.CarrierAccountParametersConverter))]
    public class CarrierAccountParameters
    {
        public CarrierAccountParameters(CarrierAccountParametersType type)
        {
            Type = type;
        }

        [SpeakeasyMetadata("form:explode=true")]
        public Dictionary<string, object>? MapOfAny { get; set; }

        [SpeakeasyMetadata("form:explode=true")]
        public FedExConnectExistingOwnAccountParameters? FedExConnectExistingOwnAccountParameters { get; set; }

        [SpeakeasyMetadata("form:explode=true")]
        public UPSConnectExistingOwnAccountParameters? UPSConnectExistingOwnAccountParameters { get; set; }

        public CarrierAccountParametersType Type { get; set; }
        public static CarrierAccountParameters CreateMapOfAny(Dictionary<string, object> mapOfAny)
        {
            CarrierAccountParametersType typ = CarrierAccountParametersType.MapOfAny;

            CarrierAccountParameters res = new CarrierAccountParameters(typ);
            res.MapOfAny = mapOfAny;
            return res;
        }
        public static CarrierAccountParameters CreateFedExConnectExistingOwnAccountParameters(FedExConnectExistingOwnAccountParameters fedExConnectExistingOwnAccountParameters)
        {
            CarrierAccountParametersType typ = CarrierAccountParametersType.FedExConnectExistingOwnAccountParameters;

            CarrierAccountParameters res = new CarrierAccountParameters(typ);
            res.FedExConnectExistingOwnAccountParameters = fedExConnectExistingOwnAccountParameters;
            return res;
        }
        public static CarrierAccountParameters CreateUPSConnectExistingOwnAccountParameters(UPSConnectExistingOwnAccountParameters upsConnectExistingOwnAccountParameters)
        {
            CarrierAccountParametersType typ = CarrierAccountParametersType.UPSConnectExistingOwnAccountParameters;

            CarrierAccountParameters res = new CarrierAccountParameters(typ);
            res.UPSConnectExistingOwnAccountParameters = upsConnectExistingOwnAccountParameters;
            return res;
        }

        public class CarrierAccountParametersConverter : JsonConverter
        {
            public override bool CanConvert(System.Type objectType) => objectType == typeof(CarrierAccountParameters);

            public override bool CanRead => true;

            public override object? ReadJson(JsonReader reader, System.Type objectType, object? existingValue, JsonSerializer serializer)
            {
                if (reader.TokenType == JsonToken.Null)
                {
                    throw new InvalidOperationException("Received unexpected null JSON value");
                }

                var json = JRaw.Create(reader).ToString();
                var fallbackCandidates = new List<(System.Type, object, string)>();

                try
                {
                    return new CarrierAccountParameters(CarrierAccountParametersType.FedExConnectExistingOwnAccountParameters)
                    {
                        FedExConnectExistingOwnAccountParameters = ResponseBodyDeserializer.DeserializeUndiscriminatedUnionMember<FedExConnectExistingOwnAccountParameters>(json)
                    };
                }
                catch (ResponseBodyDeserializer.MissingMemberException)
                {
                    fallbackCandidates.Add((typeof(FedExConnectExistingOwnAccountParameters), new CarrierAccountParameters(CarrierAccountParametersType.FedExConnectExistingOwnAccountParameters), "FedExConnectExistingOwnAccountParameters"));
                }
                catch (ResponseBodyDeserializer.DeserializationException)
                {
                    // try next option
                }
                catch (Exception)
                {
                    throw;
                }

                try
                {
                    return new CarrierAccountParameters(CarrierAccountParametersType.UPSConnectExistingOwnAccountParameters)
                    {
                        UPSConnectExistingOwnAccountParameters = ResponseBodyDeserializer.DeserializeUndiscriminatedUnionMember<UPSConnectExistingOwnAccountParameters>(json)
                    };
                }
                catch (ResponseBodyDeserializer.MissingMemberException)
                {
                    fallbackCandidates.Add((typeof(UPSConnectExistingOwnAccountParameters), new CarrierAccountParameters(CarrierAccountParametersType.UPSConnectExistingOwnAccountParameters), "UPSConnectExistingOwnAccountParameters"));
                }
                catch (ResponseBodyDeserializer.DeserializationException)
                {
                    // try next option
                }
                catch (Exception)
                {
                    throw;
                }

                try
                {
                    return new CarrierAccountParameters(CarrierAccountParametersType.MapOfAny)
                    {
                        MapOfAny = ResponseBodyDeserializer.DeserializeUndiscriminatedUnionMember<Dictionary<string, object>>(json)
                    };
                }
                catch (ResponseBodyDeserializer.MissingMemberException)
                {
                    fallbackCandidates.Add((typeof(Dictionary<string, object>), new CarrierAccountParameters(CarrierAccountParametersType.MapOfAny), "MapOfAny"));
                }
                catch (ResponseBodyDeserializer.DeserializationException)
                {
                    // try next option
                }
                catch (Exception)
                {
                    throw;
                }

                if (fallbackCandidates.Count > 0)
                {
                    fallbackCandidates.Sort((a, b) => ResponseBodyDeserializer.CompareFallbackCandidates(a.Item1, b.Item1, json));
                    foreach(var (deserializationType, returnObject, propertyName) in fallbackCandidates)
                    {
                        try
                        {
                            return ResponseBodyDeserializer.DeserializeUndiscriminatedUnionFallback(deserializationType, returnObject, propertyName, json);
                        }
                        catch (ResponseBodyDeserializer.DeserializationException)
                        {
                            // try next fallback option
                        }
                        catch (Exception)
                        {
                            throw;
                        }
                    }
                }

                throw new InvalidOperationException("Could not deserialize into any supported types.");
            }

            public override void WriteJson(JsonWriter writer, object? value, JsonSerializer serializer)
            {
                if (value == null)
                {
                    throw new InvalidOperationException("Unexpected null JSON value.");
                }

                CarrierAccountParameters res = (CarrierAccountParameters)value;

                if (res.MapOfAny != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.MapOfAny));
                    return;
                }

                if (res.FedExConnectExistingOwnAccountParameters != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.FedExConnectExistingOwnAccountParameters));
                    return;
                }

                if (res.UPSConnectExistingOwnAccountParameters != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.UPSConnectExistingOwnAccountParameters));
                    return;
                }
            }

        }

    }
}