//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Shippo.Models.Components
{
    using Newtonsoft.Json;
    using Shippo.Utils;
    
    /// <summary>
    /// Contains details regarding the service level for the carrier account.
    /// </summary>
    public class CarrierAccountServiceLevel
    {

        /// <summary>
        /// Service level name, e.g. `Priority Mail` or `FedEx Ground®`. <br/>
        /// 
        /// <remarks>
        /// A service level commonly defines the transit time of a Shipment (e.g., Express vs. Standard), along with other properties. <br/>
        /// These names vary depending on the provider.&lt;br&gt;<br/>
        /// See &lt;a href=&quot;#tag/Service-Levels&quot;&gt;Service Levels&lt;/a&gt;.
        /// </remarks>
        /// </summary>
        [JsonProperty("name")]
        public string? Name { get; set; }

        /// <summary>
        /// Service level token, e.g. `usps_priority` or `fedex_ground`.&lt;br&gt;<br/>
        /// 
        /// <remarks>
        /// See &lt;a href=&quot;#tag/Service-Levels&quot;&gt;Service Levels&lt;/a&gt;.
        /// </remarks>
        /// </summary>
        [JsonProperty("token")]
        public string? Token { get; set; }

        /// <summary>
        /// Whether or not the service level supports return labels.
        /// </summary>
        [JsonProperty("supports_return_labels")]
        public bool? SupportsReturnLabels { get; set; }
    }
}