//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Shippo.Models.Components
{
    using Newtonsoft.Json;
    using Shippo.Models.Components;
    using Shippo.Utils;
    
    public class CarrierParcelTemplate
    {

        /// <summary>
        /// The name of the carrier that provides this parcel template
        /// </summary>
        [JsonProperty("carrier")]
        public string? Carrier { get; set; }

        /// <summary>
        /// The measure unit used for length, width and height.
        /// </summary>
        [JsonProperty("distance_unit")]
        public DistanceUnitEnum? DistanceUnit { get; set; }

        /// <summary>
        /// The height of the package, in units specified by the distance_unit attribute
        /// </summary>
        [JsonProperty("height")]
        public string? Height { get; set; }

        /// <summary>
        /// True if the carrier parcel template allows custom dimensions, such as USPS Softpack.
        /// </summary>
        [JsonProperty("is_variable_dimensions")]
        public bool? IsVariableDimensions { get; set; }

        /// <summary>
        /// The length of the package, in units specified by the distance_unit attribute
        /// </summary>
        [JsonProperty("length")]
        public string? Length { get; set; }

        /// <summary>
        /// The name of the carrier parcel template
        /// </summary>
        [JsonProperty("name")]
        public string? Name { get; set; }

        /// <summary>
        /// The unique string representation of the carrier parcel template
        /// </summary>
        [JsonProperty("token")]
        public string? Token { get; set; }

        /// <summary>
        /// The width of the package, in units specified by the distance_unit attribute
        /// </summary>
        [JsonProperty("width")]
        public string? Width { get; set; }
    }
}