//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Shippo.Models.Components
{
    using Newtonsoft.Json;
    using Shippo.Utils;
    using System;
    
    public class CarrierAccountRegistrationStatus
    {

        [JsonProperty("carrier_account")]
        public string? CarrierAccount { get; set; }

        [JsonProperty("object_created")]
        public DateTime? ObjectCreated { get; set; }

        [JsonProperty("object_owner")]
        public string? ObjectOwner { get; set; }

        [JsonProperty("object_updated")]
        public DateTime? ObjectUpdated { get; set; }

        [JsonProperty("status")]
        public string? Status { get; set; }
    }
}