//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Shippo.Models.Components
{
    using Newtonsoft.Json;
    using Shippo.Models.Components;
    using Shippo.Utils;

    public class CarrierAccountBase
    {
        /// <summary>
        /// Unique identifier of the account. Please check the <a href="https://docs.goshippo.com/docs/carriers/carrieraccounts/">carrier accounts tutorial</a> <br/>
        /// page for the `account_id` per carrier.&lt;br&gt; <br/>
        /// To protect account information, this field will be masked in any API response.
        /// </summary>
        [JsonProperty("account_id")]
        public string AccountId { get; set; } = default!;

        /// <summary>
        /// Determines whether the account is active. When creating a shipment, if no `carrier_accounts` are explicitly <br/>
        /// passed Shippo will query all carrier accounts that have this field set. By default, this is set to True.
        /// </summary>
        [JsonProperty("active")]
        public bool? Active { get; set; }

        /// <summary>
        /// Carrier token, see <a href="/shippoapi/public-api/carriers">Carriers</a>&lt;br&gt;<br/>
        /// Please check the <a href="https://docs.goshippo.com/docs/carriers/carrieraccounts/">carrier accounts tutorial</a> page for all supported carriers.
        /// </summary>
        [JsonProperty("carrier")]
        public string Carrier { get; set; } = default!;

        [JsonProperty("parameters", NullValueHandling = NullValueHandling.Include)]
        public CarrierAccountBaseParameters? Parameters { get; set; }
    }
}