//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Shippo.Models.Components
{
    using Newtonsoft.Json;
    using Shippo.Utils;
    
    /// <summary>
    /// Container for specifying the presence of lithium batteries.
    /// </summary>
    public class DangerousGoodsLithiumBatteries
    {

        /// <summary>
        /// Indicates if the shipment contains lithium batteries.
        /// </summary>
        [JsonProperty("contains")]
        public bool? Contains { get; set; }
    }
}