//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Shippo.Models.Components
{
    using Newtonsoft.Json.Linq;
    using Newtonsoft.Json;
    using Shippo.Models.Components;
    using Shippo.Utils;
    using System.Numerics;
    using System;
    

    public class ParcelsType
    {
        private ParcelsType(string value) { Value = value; }

        public string Value { get; private set; }
        public static ParcelsType ParcelCreateRequest { get { return new ParcelsType("ParcelCreateRequest"); } }
        
        public static ParcelsType Str { get { return new ParcelsType("str"); } }
        
        public static ParcelsType Null { get { return new ParcelsType("null"); } }

        public override string ToString() { return Value; }
        public static implicit operator String(ParcelsType v) { return v.Value; }
        public static ParcelsType FromString(string v) {
            switch(v) {
                case "ParcelCreateRequest": return ParcelCreateRequest;
                case "str": return Str;
                case "null": return Null;
                default: throw new ArgumentException("Invalid value for ParcelsType");
            }
        }
        public override bool Equals(object? obj)
        {
            if (obj == null || GetType() != obj.GetType())
            {
                return false;
            }
            return Value.Equals(((ParcelsType)obj).Value);
        }

        public override int GetHashCode()
        {
            return Value.GetHashCode();
        }
    }
    

    [JsonConverter(typeof(Parcels.ParcelsConverter))]
    public class Parcels {
        public Parcels(ParcelsType type) {
            Type = type;
        }
        public ParcelCreateRequest? ParcelCreateRequest { get; set; } 
        public string? Str { get; set; } 

        public ParcelsType Type { get; set; }


        public static Parcels CreateParcelCreateRequest(ParcelCreateRequest parcelCreateRequest) {
            ParcelsType typ = ParcelsType.ParcelCreateRequest;

            Parcels res = new Parcels(typ);
            res.ParcelCreateRequest = parcelCreateRequest;
            return res;
        }

        public static Parcels CreateStr(string str) {
            ParcelsType typ = ParcelsType.Str;

            Parcels res = new Parcels(typ);
            res.Str = str;
            return res;
        }

        public static Parcels CreateNull() {
            ParcelsType typ = ParcelsType.Null;
            return new Parcels(typ);
        }

        public class ParcelsConverter : JsonConverter
        {

            public override bool CanConvert(System.Type objectType) => objectType == typeof(Parcels);

            public override bool CanRead => true;

            public override object? ReadJson(JsonReader reader, System.Type objectType, object? existingValue, JsonSerializer serializer)
            { 
                var json = JRaw.Create(reader).ToString();

                if (json == "null") {
                    return null;
                }
                try
                {
                    ParcelCreateRequest? parcelCreateRequest = ResponseBodyDeserializer.Deserialize<ParcelCreateRequest>(json, missingMemberHandling: MissingMemberHandling.Error);
                    return new Parcels(ParcelsType.ParcelCreateRequest) {
                        ParcelCreateRequest = parcelCreateRequest
                    };
                }
                catch (Exception ex)
                {
                    if (!(ex is Newtonsoft.Json.JsonReaderException || ex is Newtonsoft.Json.JsonSerializationException)) {
                        throw ex;
                    }
                }
                if (json[0] == '"' && json[^1] == '"'){
                    return new Parcels(ParcelsType.Str) {
                        Str = json[1..^1]
                    };
                }

                throw new InvalidOperationException("Could not deserialize into any supported types.");
            }

            public override void WriteJson(JsonWriter writer, object? value, JsonSerializer serializer)
            {
                if (value == null) {
                    writer.WriteRawValue("null");
                    return;
                }
                Parcels res = (Parcels)value;
                if (ParcelsType.FromString(res.Type).Equals(ParcelsType.Null))
                {
                    writer.WriteRawValue("null");
                    return;
                }
                if (res.ParcelCreateRequest != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.ParcelCreateRequest));
                    return;
                }
                if (res.Str != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.Str));
                    return;
                }

            }
        }

    }

}