//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Shippo.Models.Components
{
    using Newtonsoft.Json;
    using Shippo.Utils;
    using System;
    
    /// <summary>
    /// Secured funds include money orders, certified cheques and others (see <br/>
    /// 
    /// <remarks>
    /// &lt;a href=&quot;https://www.ups.com/content/us/en/shipping/time/service/value_added/cod.html&quot;&gt;UPS&lt;/a&gt; for details). <br/>
    /// If no payment_method inputted the value defaults to &quot;ANY&quot;.)
    /// </remarks>
    /// </summary>
    public enum PaymentMethod
    {
        [JsonProperty("SECURED_FUNDS")]
        SecuredFunds,
        [JsonProperty("CASH")]
        Cash,
        [JsonProperty("ANY")]
        Any,
    }

    public static class PaymentMethodExtension
    {
        public static string Value(this PaymentMethod value)
        {
            return ((JsonPropertyAttribute)value.GetType().GetMember(value.ToString())[0].GetCustomAttributes(typeof(JsonPropertyAttribute), false)[0]).PropertyName ?? value.ToString();
        }

        public static PaymentMethod ToEnum(this string value)
        {
            foreach(var field in typeof(PaymentMethod).GetFields())
            {
                var attributes = field.GetCustomAttributes(typeof(JsonPropertyAttribute), false);
                if (attributes.Length == 0)
                {
                    continue;
                }

                var attribute = attributes[0] as JsonPropertyAttribute;
                if (attribute != null && attribute.PropertyName == value)
                {
                    var enumVal = field.GetValue(null);

                    if (enumVal is PaymentMethod)
                    {
                        return (PaymentMethod)enumVal;
                    }
                }
            }

            throw new Exception($"Unknown value {value} for enum PaymentMethod");
        }
    }

}