//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Shippo.Models.Components
{
    using Newtonsoft.Json;
    using Shippo.Utils;
    using System;
    
    /// <summary>
    /// |Token | Service name|<br/>
    /// 
    /// <remarks>
    /// |:---|:---|<br/>
    /// | dhl_express_domestic_express_doc | Domestic Express Doc|<br/>
    /// | dhl_express_economy_select_doc | Economy Select Doc|<br/>
    /// | dhl_express_worldwide_nondoc | Express Worldwide Nondoc|<br/>
    /// | dhl_express_worldwide_doc | Express Worldwide Doc|<br/>
    /// | dhl_express_worldwide | Worldwide|<br/>
    /// | dhl_express_worldwide_eu_doc | Express Worldwide EU Doc|<br/>
    /// | dhl_express_break_bulk_express_doc | Break Bulk Express Doc|<br/>
    /// | dhl_express_express_9_00_nondoc | Express 9:00 NonDoc|<br/>
    /// | dhl_express_economy_select_nondoc | Economy Select NonDoc|<br/>
    /// | dhl_express_break_bulk_economy_doc | Break Bulk Economy Doc|<br/>
    /// | dhl_express_express_9_00_doc | Express 9:00 Doc|<br/>
    /// | dhl_express_express_10_30_doc | Express 10:30 Doc|<br/>
    /// | dhl_express_express_10_30_nondoc | Express 10:30 NonDoc|<br/>
    /// | dhl_express_express_12_00_doc | Express 12:00 Doc|<br/>
    /// | dhl_express_europack_nondoc | Europack NonDoc|<br/>
    /// | dhl_express_express_envelope_doc | Express Envelope Doc|<br/>
    /// | dhl_express_express_12_00_nondoc | Express 12:00 NonDoc|<br/>
    /// | dhl_express_express_12_doc | Domestic Express 12:00|<br/>
    /// | dhl_express_worldwide_b2c_doc | Express Worldwide (B2C) Doc|<br/>
    /// | dhl_express_worldwide_b2c_nondoc | Express Worldwide (B2C) NonDoc|<br/>
    /// | dhl_express_medical_express | Medical Express|<br/>
    /// | dhl_express_express_easy_nondoc | Express Easy NonDoc|<br/>
    /// 
    /// </remarks>
    /// </summary>
    public enum ServiceLevelDHLExpressEnum
    {
        [JsonProperty("dhl_express_domestic_express_doc")]
        DhlExpressDomesticExpressDoc,
        [JsonProperty("dhl_express_economy_select_doc")]
        DhlExpressEconomySelectDoc,
        [JsonProperty("dhl_express_worldwide_nondoc")]
        DhlExpressWorldwideNondoc,
        [JsonProperty("dhl_express_worldwide_doc")]
        DhlExpressWorldwideDoc,
        [JsonProperty("dhl_express_worldwide")]
        DhlExpressWorldwide,
        [JsonProperty("dhl_express_worldwide_eu_doc")]
        DhlExpressWorldwideEuDoc,
        [JsonProperty("dhl_express_break_bulk_express_doc")]
        DhlExpressBreakBulkExpressDoc,
        [JsonProperty("dhl_express_express_9_00_nondoc")]
        DhlExpressExpress900Nondoc,
        [JsonProperty("dhl_express_economy_select_nondoc")]
        DhlExpressEconomySelectNondoc,
        [JsonProperty("dhl_express_break_bulk_economy_doc")]
        DhlExpressBreakBulkEconomyDoc,
        [JsonProperty("dhl_express_express_9_00_doc")]
        DhlExpressExpress900Doc,
        [JsonProperty("dhl_express_express_10_30_doc")]
        DhlExpressExpress1030Doc,
        [JsonProperty("dhl_express_express_10_30_nondoc")]
        DhlExpressExpress1030Nondoc,
        [JsonProperty("dhl_express_express_12_00_doc")]
        DhlExpressExpress1200Doc,
        [JsonProperty("dhl_express_europack_nondoc")]
        DhlExpressEuropackNondoc,
        [JsonProperty("dhl_express_express_envelope_doc")]
        DhlExpressExpressEnvelopeDoc,
        [JsonProperty("dhl_express_express_12_00_nondoc")]
        DhlExpressExpress1200Nondoc,
        [JsonProperty("dhl_express_express_12_doc")]
        DhlExpressExpress12Doc,
        [JsonProperty("dhl_express_worldwide_b2c_doc")]
        DhlExpressWorldwideB2cDoc,
        [JsonProperty("dhl_express_worldwide_b2c_nondoc")]
        DhlExpressWorldwideB2cNondoc,
        [JsonProperty("dhl_express_medical_express")]
        DhlExpressMedicalExpress,
        [JsonProperty("dhl_express_express_easy_nondoc")]
        DhlExpressExpressEasyNondoc,
    }

    public static class ServiceLevelDHLExpressEnumExtension
    {
        public static string Value(this ServiceLevelDHLExpressEnum value)
        {
            return ((JsonPropertyAttribute)value.GetType().GetMember(value.ToString())[0].GetCustomAttributes(typeof(JsonPropertyAttribute), false)[0]).PropertyName ?? value.ToString();
        }

        public static ServiceLevelDHLExpressEnum ToEnum(this string value)
        {
            foreach(var field in typeof(ServiceLevelDHLExpressEnum).GetFields())
            {
                var attributes = field.GetCustomAttributes(typeof(JsonPropertyAttribute), false);
                if (attributes.Length == 0)
                {
                    continue;
                }

                var attribute = attributes[0] as JsonPropertyAttribute;
                if (attribute != null && attribute.PropertyName == value)
                {
                    var enumVal = field.GetValue(null);

                    if (enumVal is ServiceLevelDHLExpressEnum)
                    {
                        return (ServiceLevelDHLExpressEnum)enumVal;
                    }
                }
            }

            throw new Exception($"Unknown value {value} for enum ServiceLevelDHLExpressEnum");
        }
    }

}