//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Shippo.Models.Components
{
    using Newtonsoft.Json;
    using Shippo.Utils;
    using System;
    
    /// <summary>
    /// |Token | Service name|<br/>
    /// 
    /// <remarks>
    /// |:---|:---|<br/>
    /// | better_trucks_same_day | Same Day|<br/>
    /// | better_trucks_next_day | Next Day|<br/>
    /// 
    /// </remarks>
    /// </summary>
    public enum ServiceLevelBetterTrucksEnum
    {
        [JsonProperty("better_trucks_same_day")]
        BetterTrucksSameDay,
        [JsonProperty("better_trucks_next_day")]
        BetterTrucksNextDay,
    }

    public static class ServiceLevelBetterTrucksEnumExtension
    {
        public static string Value(this ServiceLevelBetterTrucksEnum value)
        {
            return ((JsonPropertyAttribute)value.GetType().GetMember(value.ToString())[0].GetCustomAttributes(typeof(JsonPropertyAttribute), false)[0]).PropertyName ?? value.ToString();
        }

        public static ServiceLevelBetterTrucksEnum ToEnum(this string value)
        {
            foreach(var field in typeof(ServiceLevelBetterTrucksEnum).GetFields())
            {
                var attributes = field.GetCustomAttributes(typeof(JsonPropertyAttribute), false);
                if (attributes.Length == 0)
                {
                    continue;
                }

                var attribute = attributes[0] as JsonPropertyAttribute;
                if (attribute != null && attribute.PropertyName == value)
                {
                    var enumVal = field.GetValue(null);

                    if (enumVal is ServiceLevelBetterTrucksEnum)
                    {
                        return (ServiceLevelBetterTrucksEnum)enumVal;
                    }
                }
            }

            throw new Exception($"Unknown value {value} for enum ServiceLevelBetterTrucksEnum");
        }
    }

}