//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Shippo.Models.Components
{
    using Newtonsoft.Json;
    using Shippo.Utils;
    using System;
    
    /// <summary>
    /// |Token | Service name|<br/>
    /// 
    /// <remarks>
    /// |:---|:---|<br/>
    /// | dpd_uk_ship_to_shop | Ship to shop|<br/>
    /// | dpd_uk_1030 | Door to door 10.30 next day|<br/>
    /// | dpd_uk_1200 | Door to door 12.00 next day|<br/>
    /// | dpd_uk_saturday | Saturday Delivery|<br/>
    /// | dpd_uk_saturday_1030 | Saturday Delivery 10.30|<br/>
    /// | dpd_uk_saturday_1200 | Saturday Delivery 12.00|<br/>
    /// | dpd_uk_sunday | Sunday Delivery|<br/>
    /// | dpd_uk_sunday_1030 | Sunday Delivery 10.30|<br/>
    /// | dpd_uk_sunday_1200 | Sunday Delivery 12.00|<br/>
    /// | dpd_uk_next_day | Next day|<br/>
    /// | dpd_uk_two_day | Two day|<br/>
    /// | dpd_uk_classic | DPD Classic|<br/>
    /// | dpd_uk_air_classic | DPD Air Classic|<br/>
    /// | dpd_uk_air_express | DPD Air Express|<br/>
    /// | dpd_uk_direct | DPD Direct|<br/>
    /// | dpd_uk_direct_tracked_mail| DPD Tracked Mail|<br/>
    /// | dpd_uk_pickup_returns | Pickup Returns|<br/>
    /// 
    /// </remarks>
    /// </summary>
    public enum ServiceLevelDPDUKEnum
    {
        [JsonProperty("dpd_uk_ship_to_shop")]
        DpdUkShipToShop,
        [JsonProperty("dpd_uk_1030")]
        DpdUk1030,
        [JsonProperty("dpd_uk_1200")]
        DpdUk1200,
        [JsonProperty("dpd_uk_saturday")]
        DpdUkSaturday,
        [JsonProperty("dpd_uk_saturday_1030")]
        DpdUkSaturday1030,
        [JsonProperty("dpd_uk_saturday_1200")]
        DpdUkSaturday1200,
        [JsonProperty("dpd_uk_sunday")]
        DpdUkSunday,
        [JsonProperty("dpd_uk_sunday_1030")]
        DpdUkSunday1030,
        [JsonProperty("dpd_uk_sunday_1200")]
        DpdUkSunday1200,
        [JsonProperty("dpd_uk_next_day")]
        DpdUkNextDay,
        [JsonProperty("dpd_uk_two_day")]
        DpdUkTwoDay,
        [JsonProperty("dpd_uk_classic")]
        DpdUkClassic,
        [JsonProperty("dpd_uk_air_classic")]
        DpdUkAirClassic,
        [JsonProperty("dpd_uk_air_express")]
        DpdUkAirExpress,
        [JsonProperty("dpd_uk_direct")]
        DpdUkDirect,
        [JsonProperty("dpd_uk_direct_tracked_mail")]
        DpdUkDirectTrackedMail,
        [JsonProperty("dpd_uk_pickup_returns")]
        DpdUkPickupReturns,
    }

    public static class ServiceLevelDPDUKEnumExtension
    {
        public static string Value(this ServiceLevelDPDUKEnum value)
        {
            return ((JsonPropertyAttribute)value.GetType().GetMember(value.ToString())[0].GetCustomAttributes(typeof(JsonPropertyAttribute), false)[0]).PropertyName ?? value.ToString();
        }

        public static ServiceLevelDPDUKEnum ToEnum(this string value)
        {
            foreach(var field in typeof(ServiceLevelDPDUKEnum).GetFields())
            {
                var attributes = field.GetCustomAttributes(typeof(JsonPropertyAttribute), false);
                if (attributes.Length == 0)
                {
                    continue;
                }

                var attribute = attributes[0] as JsonPropertyAttribute;
                if (attribute != null && attribute.PropertyName == value)
                {
                    var enumVal = field.GetValue(null);

                    if (enumVal is ServiceLevelDPDUKEnum)
                    {
                        return (ServiceLevelDPDUKEnum)enumVal;
                    }
                }
            }

            throw new Exception($"Unknown value {value} for enum ServiceLevelDPDUKEnum");
        }
    }

}