//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Shippo.Models.Components
{
    using Newtonsoft.Json;
    using Shippo.Utils;

    /// <summary>
    /// A finer-grained classification of the tracking event.
    /// </summary>
    public class TrackingStatusSubstatus
    {
        /// <summary>
        /// A code that represents the substatus of the shipment. See the <a href="https://docs.goshippo.com/docs/tracking/tracking/#event-definitions">Event Definitions</a> for more information.
        /// </summary>
        [JsonProperty("code")]
        public string Code { get; set; } = default!;

        /// <summary>
        /// A human-readable description of the substatus. See the <a href="https://docs.goshippo.com/docs/tracking/tracking/#event-definitions">Event Definitions</a> for more information.
        /// </summary>
        [JsonProperty("text")]
        public string Text { get; set; } = default!;

        /// <summary>
        /// Indicates whether the substatus requires action from the shipper or recipient to complete delivery.
        /// </summary>
        [JsonProperty("action_required")]
        public bool ActionRequired { get; set; } = default!;
    }
}