//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Shippo.Models.Components
{
    using Newtonsoft.Json;
    using Shippo.Utils;
    
    public class UPSReferenceFields
    {

        /// <summary>
        /// Custom prefix text.
        /// </summary>
        [JsonProperty("prefix")]
        public string? Prefix { get; set; }

        /// <summary>
        /// Label reference text. 35 character limit.
        /// </summary>
        [JsonProperty("value")]
        public string? Value { get; set; }

        /// <summary>
        /// Order UPS reference fields are printed on ZPL labels. For UPS shipments, if you choose to set `ref_sort` for one reference, you must set `ref_sort` for all other supported UPS references using unique integers.
        /// </summary>
        [JsonProperty("ref_sort")]
        public long? RefSort { get; set; }
    }
}