//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Shippo.Models.Components
{
    using Newtonsoft.Json;
    using Shippo.Models.Components;
    using Shippo.Utils;
    using System;
    
    public class UserParcelTemplate
    {

        /// <summary>
        /// The measure unit used for length, width and height.
        /// </summary>
        [JsonProperty("distance_unit")]
        public DistanceUnitEnum? DistanceUnit { get; set; }

        /// <summary>
        /// The height of the package, in units specified by the `distance_unit` attribute. Required, but if using a preset carrier template then this field must be empty.
        /// </summary>
        [JsonProperty("height")]
        public string? Height { get; set; }

        /// <summary>
        /// The length of the package, in units specified by the `distance_unit` attribute. Required, but if using a preset carrier template then this field must be empty.
        /// </summary>
        [JsonProperty("length")]
        public string? Length { get; set; }

        /// <summary>
        /// The name of the User Parcel Template
        /// </summary>
        [JsonProperty("name")]
        public string? Name { get; set; }

        /// <summary>
        /// The weight of the package, in units specified by the weight_unit attribute.
        /// </summary>
        [JsonProperty("weight")]
        public string? Weight { get; set; }

        /// <summary>
        /// The unit used for weight.
        /// </summary>
        [JsonProperty("weight_unit")]
        public WeightUnitEnum? WeightUnit { get; set; }

        /// <summary>
        /// The width of the package, in units specified by the `distance_unit` attribute. Required, but if using a preset carrier template then this field must be empty.
        /// </summary>
        [JsonProperty("width")]
        public string? Width { get; set; }

        /// <summary>
        /// Date and time of User Parcel Template creation
        /// </summary>
        [JsonProperty("object_created")]
        public DateTime? ObjectCreated { get; set; }

        /// <summary>
        /// Unique identifier of the given User Parcel Template object
        /// </summary>
        [JsonProperty("object_id")]
        public string? ObjectId { get; set; }

        /// <summary>
        /// Username of the user who created the User Parcel Template object
        /// </summary>
        [JsonProperty("object_owner")]
        public string? ObjectOwner { get; set; }

        /// <summary>
        /// Date and time of last update on User Parcel Template
        /// </summary>
        [JsonProperty("object_updated")]
        public DateTime? ObjectUpdated { get; set; }

        [JsonProperty("template")]
        public CarrierParcelTemplate? Template { get; set; }
    }
}