//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Shippo.Models.Components
{
    using Newtonsoft.Json;
    using Shippo.Models.Components;
    using Shippo.Utils;
    
    public class WebhookUpdateRequest
    {

        /// <summary>
        /// Type of event that triggered the webhook.
        /// </summary>
        [JsonProperty("event")]
        public WebhookEventTypeEnum Event { get; set; } = default!;

        /// <summary>
        /// URL webhook events are sent to.
        /// </summary>
        [JsonProperty("url")]
        public string Url { get; set; } = default!;

        /// <summary>
        /// Determines whether the webhook is active or not.
        /// </summary>
        [JsonProperty("active")]
        public bool? Active { get; set; }

        /// <summary>
        /// Determines whether the webhook is a test webhook or not.
        /// </summary>
        [JsonProperty("is_test")]
        public bool? IsTest { get; set; }
    }
}