//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Shippo.Models.Errors
{
    using System;
    using System.Net.Http;

    public class SDKException : Exception
    {

        public override string Message { get; }
        public HttpRequestMessage Request { get; set; }
        public HttpResponseMessage Response { get; set; }
        public SDKException(string message, HttpRequestMessage request, HttpResponseMessage response)
        {
            Message = message;
            Request = request;
            Response = response;
        }

        public override string ToString(){
            return Message + ": Status " + Response.StatusCode;
        }

    }
}
