name: Publish

permissions:
  checks: write
  contents: write
  pull-requests: write
  statuses: write

on:
  push:
    branches:
      - main
    paths:
      - RELEASES.md
      - "*/RELEASES.md"

jobs:
  publish:
    uses: speakeasy-api/sdk-generation-action/.github/workflows/sdk-publish.yaml@v15
    secrets:
      github-app-id: ${{ vars.GH_APP_ID }}
      github-app-private-key: ${{ secrets.GH_APP_PRIVATE_KEY }}
      nuget_api_key: ${{ secrets.NUGET_API_KEY }}
      speakeasy_api_key: ${{ secrets.SPEAKEASY_API_KEY }}
